version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: audit_tale_mysql_db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=audit_tale
      - MYSQL_PASSWORD=audit_tale
      - MYSQL_DATABASE=audit_tale
      - MYSQL_ROOT_PASSWORD=audit_tale

